### ISSUE TITLE
Provide standard CRUD endpoints for projects and todo items

### ISSUE THREAD

**Issue by whitneyfirth** [whitneyburton/todo-be#3]
- [x] Require authentication and validate access to resources (Use 401/403 response codes accordingly)
- [x] Respond with accurate and meaningful information (Use appropriate HTTP code (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes))
- [x] Supply relevant error/success information in the response body
